databases:
  - name: rails_budget_app_production

services:
  - type: web
    name: rails-budget-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_budget_app_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false